[tool.poetry]
name = "m-django-extensions"
version = "0.1.0"
description = ""
authors = ["Artem <artem@dobroagency.ru>"]
readme = "README.md"
packages = [
    {include = "fields"}
]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.4"
pillow = "^10.0.0"
setuptools = "^68.0.0"
twine = "^4.0.2"
wheel = "^0.41.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
