# Generated by Django 6.0.5 on 2026-05-19 08:54

import m_django_extensions.s3filefield
import tests.testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', m_django_extensions.s3filefield.S3FileField(upload_to='documents/%Y/%m/')),
                ('callable_file', m_django_extensions.s3filefield.S3FileField(upload_to=tests.testapp.models.upload_to_callable)),
            ],
        ),
    ]
